name: CI - Solidity Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      
    - name: Run solhint
      run: npx solhint 'contracts/**/*.sol'

    - name: Compile contracts
      run: npx hardhat compile

    - name: Install Slither
      run: python3 -m pip install --user slither-analyzer

    - name: Run Slither
      continue-on-error: true
      run: python3 -m slither . --exclude-dependencies --exclude naming-convention
      
    - name: Run tests
      run: npx hardhat test
      
    - name: Run coverage
      run: npx hardhat coverage
